// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.3
// source: protos/ai.proto

package aiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ModelType int32

const (
	ModelType_MODEL_UNSPECIFIED ModelType = 0
	ModelType_IMAGE_MODEL       ModelType = 1
	ModelType_TEXT_MODEL        ModelType = 2
)

// Enum value maps for ModelType.
var (
	ModelType_name = map[int32]string{
		0: "MODEL_UNSPECIFIED",
		1: "IMAGE_MODEL",
		2: "TEXT_MODEL",
	}
	ModelType_value = map[string]int32{
		"MODEL_UNSPECIFIED": 0,
		"IMAGE_MODEL":       1,
		"TEXT_MODEL":        2,
	}
)

func (x ModelType) Enum() *ModelType {
	p := new(ModelType)
	*p = x
	return p
}

func (x ModelType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ModelType) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_ai_proto_enumTypes[0].Descriptor()
}

func (ModelType) Type() protoreflect.EnumType {
	return &file_protos_ai_proto_enumTypes[0]
}

func (x ModelType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ModelType.Descriptor instead.
func (ModelType) EnumDescriptor() ([]byte, []int) {
	return file_protos_ai_proto_rawDescGZIP(), []int{0}
}

type GenerateImageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int64                  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Promt         string                 `protobuf:"bytes,2,opt,name=promt,proto3" json:"promt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateImageRequest) Reset() {
	*x = GenerateImageRequest{}
	mi := &file_protos_ai_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateImageRequest) ProtoMessage() {}

func (x *GenerateImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_ai_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateImageRequest.ProtoReflect.Descriptor instead.
func (*GenerateImageRequest) Descriptor() ([]byte, []int) {
	return file_protos_ai_proto_rawDescGZIP(), []int{0}
}

func (x *GenerateImageRequest) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *GenerateImageRequest) GetPromt() string {
	if x != nil {
		return x.Promt
	}
	return ""
}

type GenerateImageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateImageResponse) Reset() {
	*x = GenerateImageResponse{}
	mi := &file_protos_ai_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateImageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateImageResponse) ProtoMessage() {}

func (x *GenerateImageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_ai_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateImageResponse.ProtoReflect.Descriptor instead.
func (*GenerateImageResponse) Descriptor() ([]byte, []int) {
	return file_protos_ai_proto_rawDescGZIP(), []int{1}
}

func (x *GenerateImageResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type ChangeModelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          ModelType              `protobuf:"varint,1,opt,name=type,proto3,enum=pkg.ModelType" json:"type,omitempty"`
	ModelName     string                 `protobuf:"bytes,2,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeModelRequest) Reset() {
	*x = ChangeModelRequest{}
	mi := &file_protos_ai_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeModelRequest) ProtoMessage() {}

func (x *ChangeModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_ai_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeModelRequest.ProtoReflect.Descriptor instead.
func (*ChangeModelRequest) Descriptor() ([]byte, []int) {
	return file_protos_ai_proto_rawDescGZIP(), []int{2}
}

func (x *ChangeModelRequest) GetType() ModelType {
	if x != nil {
		return x.Type
	}
	return ModelType_MODEL_UNSPECIFIED
}

func (x *ChangeModelRequest) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

type ChangeModelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeModelResponse) Reset() {
	*x = ChangeModelResponse{}
	mi := &file_protos_ai_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeModelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeModelResponse) ProtoMessage() {}

func (x *ChangeModelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_ai_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeModelResponse.ProtoReflect.Descriptor instead.
func (*ChangeModelResponse) Descriptor() ([]byte, []int) {
	return file_protos_ai_proto_rawDescGZIP(), []int{3}
}

func (x *ChangeModelResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *ChangeModelResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetInformationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInformationRequest) Reset() {
	*x = GetInformationRequest{}
	mi := &file_protos_ai_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInformationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInformationRequest) ProtoMessage() {}

func (x *GetInformationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_ai_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInformationRequest.ProtoReflect.Descriptor instead.
func (*GetInformationRequest) Descriptor() ([]byte, []int) {
	return file_protos_ai_proto_rawDescGZIP(), []int{4}
}

type GetInformationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatModel     string                 `protobuf:"bytes,1,opt,name=chat_model,json=chatModel,proto3" json:"chat_model,omitempty"`
	ImageModel    string                 `protobuf:"bytes,2,opt,name=image_model,json=imageModel,proto3" json:"image_model,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInformationResponse) Reset() {
	*x = GetInformationResponse{}
	mi := &file_protos_ai_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInformationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInformationResponse) ProtoMessage() {}

func (x *GetInformationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_ai_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInformationResponse.ProtoReflect.Descriptor instead.
func (*GetInformationResponse) Descriptor() ([]byte, []int) {
	return file_protos_ai_proto_rawDescGZIP(), []int{5}
}

func (x *GetInformationResponse) GetChatModel() string {
	if x != nil {
		return x.ChatModel
	}
	return ""
}

func (x *GetInformationResponse) GetImageModel() string {
	if x != nil {
		return x.ImageModel
	}
	return ""
}

type SuggestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int64                  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Suggest       string                 `protobuf:"bytes,2,opt,name=suggest,proto3" json:"suggest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuggestRequest) Reset() {
	*x = SuggestRequest{}
	mi := &file_protos_ai_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuggestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuggestRequest) ProtoMessage() {}

func (x *SuggestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_ai_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuggestRequest.ProtoReflect.Descriptor instead.
func (*SuggestRequest) Descriptor() ([]byte, []int) {
	return file_protos_ai_proto_rawDescGZIP(), []int{6}
}

func (x *SuggestRequest) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *SuggestRequest) GetSuggest() string {
	if x != nil {
		return x.Suggest
	}
	return ""
}

type SuggestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Request       string                 `protobuf:"bytes,2,opt,name=request,proto3" json:"request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuggestResponse) Reset() {
	*x = SuggestResponse{}
	mi := &file_protos_ai_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuggestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuggestResponse) ProtoMessage() {}

func (x *SuggestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_ai_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuggestResponse.ProtoReflect.Descriptor instead.
func (*SuggestResponse) Descriptor() ([]byte, []int) {
	return file_protos_ai_proto_rawDescGZIP(), []int{7}
}

func (x *SuggestResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *SuggestResponse) GetRequest() string {
	if x != nil {
		return x.Request
	}
	return ""
}

type ClearHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int64                  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearHistoryRequest) Reset() {
	*x = ClearHistoryRequest{}
	mi := &file_protos_ai_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearHistoryRequest) ProtoMessage() {}

func (x *ClearHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_ai_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearHistoryRequest.ProtoReflect.Descriptor instead.
func (*ClearHistoryRequest) Descriptor() ([]byte, []int) {
	return file_protos_ai_proto_rawDescGZIP(), []int{8}
}

func (x *ClearHistoryRequest) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type ClearHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearHistoryResponse) Reset() {
	*x = ClearHistoryResponse{}
	mi := &file_protos_ai_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearHistoryResponse) ProtoMessage() {}

func (x *ClearHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_ai_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearHistoryResponse.ProtoReflect.Descriptor instead.
func (*ClearHistoryResponse) Descriptor() ([]byte, []int) {
	return file_protos_ai_proto_rawDescGZIP(), []int{9}
}

func (x *ClearHistoryResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_protos_ai_proto protoreflect.FileDescriptor

var file_protos_ai_proto_rawDesc = string([]byte{
	0x0a, 0x0f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x61, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x03, 0x70, 0x6b, 0x67, 0x22, 0x3e, 0x0a, 0x14, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61,
	0x74, 0x65, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10,
	0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x75, 0x69, 0x64,
	0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x6f, 0x6d, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x70, 0x72, 0x6f, 0x6d, 0x74, 0x22, 0x29, 0x0a, 0x15, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61,
	0x74, 0x65, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72,
	0x6c, 0x22, 0x57, 0x0a, 0x12, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x4d, 0x6f, 0x64, 0x65, 0x6c,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x22, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x70, 0x6b, 0x67, 0x2e, 0x4d, 0x6f, 0x64, 0x65,
	0x6c, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x6d,
	0x6f, 0x64, 0x65, 0x6c, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x3f, 0x0a, 0x13, 0x43, 0x68,
	0x61, 0x6e, 0x67, 0x65, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f,
	0x6b, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x17, 0x0a, 0x15, 0x47,
	0x65, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x22, 0x58, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x72,
	0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1d,
	0x0a, 0x0a, 0x63, 0x68, 0x61, 0x74, 0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x63, 0x68, 0x61, 0x74, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x1f, 0x0a,
	0x0b, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x22, 0x3c,
	0x0a, 0x0e, 0x53, 0x75, 0x67, 0x67, 0x65, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x75,
	0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x67, 0x67, 0x65, 0x73, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x75, 0x67, 0x67, 0x65, 0x73, 0x74, 0x22, 0x3b, 0x0a, 0x0f,
	0x53, 0x75, 0x67, 0x67, 0x65, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b, 0x12,
	0x18, 0x0a, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x27, 0x0a, 0x13, 0x43, 0x6c, 0x65,
	0x61, 0x72, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x75,
	0x69, 0x64, 0x22, 0x26, 0x0a, 0x14, 0x43, 0x6c, 0x65, 0x61, 0x72, 0x48, 0x69, 0x73, 0x74, 0x6f,
	0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b, 0x2a, 0x43, 0x0a, 0x09, 0x4d, 0x6f,
	0x64, 0x65, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x12, 0x15, 0x0a, 0x11, 0x4d, 0x4f, 0x44, 0x45, 0x4c,
	0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0f,
	0x0a, 0x0b, 0x49, 0x4d, 0x41, 0x47, 0x45, 0x5f, 0x4d, 0x4f, 0x44, 0x45, 0x4c, 0x10, 0x01, 0x12,
	0x0e, 0x0a, 0x0a, 0x54, 0x45, 0x58, 0x54, 0x5f, 0x4d, 0x4f, 0x44, 0x45, 0x4c, 0x10, 0x02, 0x32,
	0xd7, 0x02, 0x0a, 0x02, 0x41, 0x69, 0x12, 0x37, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x53, 0x75, 0x67,
	0x67, 0x65, 0x73, 0x74, 0x12, 0x13, 0x2e, 0x70, 0x6b, 0x67, 0x2e, 0x53, 0x75, 0x67, 0x67, 0x65,
	0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x70, 0x6b, 0x67, 0x2e,
	0x53, 0x75, 0x67, 0x67, 0x65, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x43, 0x0a, 0x0c, 0x43, 0x6c, 0x65, 0x61, 0x72, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x12,
	0x18, 0x2e, 0x70, 0x6b, 0x67, 0x2e, 0x43, 0x6c, 0x65, 0x61, 0x72, 0x48, 0x69, 0x73, 0x74, 0x6f,
	0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x70, 0x6b, 0x67, 0x2e,
	0x43, 0x6c, 0x65, 0x61, 0x72, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x49, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x72,
	0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x2e, 0x70, 0x6b, 0x67, 0x2e, 0x47, 0x65, 0x74,
	0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x70, 0x6b, 0x67, 0x2e, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x66, 0x6f,
	0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x40, 0x0a, 0x0b, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x17,
	0x2e, 0x70, 0x6b, 0x67, 0x2e, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x4d, 0x6f, 0x64, 0x65, 0x6c,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x70, 0x6b, 0x67, 0x2e, 0x43, 0x68,
	0x61, 0x6e, 0x67, 0x65, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x46, 0x0a, 0x0d, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x49, 0x6d, 0x61,
	0x67, 0x65, 0x12, 0x19, 0x2e, 0x70, 0x6b, 0x67, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74,
	0x65, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e,
	0x70, 0x6b, 0x67, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x49, 0x6d, 0x61, 0x67,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x14, 0x5a, 0x12, 0x61, 0x6c, 0x67,
	0x6f, 0x62, 0x6f, 0x74, 0x2e, 0x61, 0x69, 0x2e, 0x76, 0x31, 0x3b, 0x61, 0x69, 0x76, 0x31, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_protos_ai_proto_rawDescOnce sync.Once
	file_protos_ai_proto_rawDescData []byte
)

func file_protos_ai_proto_rawDescGZIP() []byte {
	file_protos_ai_proto_rawDescOnce.Do(func() {
		file_protos_ai_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_ai_proto_rawDesc), len(file_protos_ai_proto_rawDesc)))
	})
	return file_protos_ai_proto_rawDescData
}

var file_protos_ai_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_protos_ai_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_protos_ai_proto_goTypes = []any{
	(ModelType)(0),                 // 0: pkg.ModelType
	(*GenerateImageRequest)(nil),   // 1: pkg.GenerateImageRequest
	(*GenerateImageResponse)(nil),  // 2: pkg.GenerateImageResponse
	(*ChangeModelRequest)(nil),     // 3: pkg.ChangeModelRequest
	(*ChangeModelResponse)(nil),    // 4: pkg.ChangeModelResponse
	(*GetInformationRequest)(nil),  // 5: pkg.GetInformationRequest
	(*GetInformationResponse)(nil), // 6: pkg.GetInformationResponse
	(*SuggestRequest)(nil),         // 7: pkg.SuggestRequest
	(*SuggestResponse)(nil),        // 8: pkg.SuggestResponse
	(*ClearHistoryRequest)(nil),    // 9: pkg.ClearHistoryRequest
	(*ClearHistoryResponse)(nil),   // 10: pkg.ClearHistoryResponse
}
var file_protos_ai_proto_depIdxs = []int32{
	0,  // 0: pkg.ChangeModelRequest.type:type_name -> pkg.ModelType
	7,  // 1: pkg.Ai.GetSuggest:input_type -> pkg.SuggestRequest
	9,  // 2: pkg.Ai.ClearHistory:input_type -> pkg.ClearHistoryRequest
	5,  // 3: pkg.Ai.GetInformation:input_type -> pkg.GetInformationRequest
	3,  // 4: pkg.Ai.ChangeModel:input_type -> pkg.ChangeModelRequest
	1,  // 5: pkg.Ai.GenerateImage:input_type -> pkg.GenerateImageRequest
	8,  // 6: pkg.Ai.GetSuggest:output_type -> pkg.SuggestResponse
	10, // 7: pkg.Ai.ClearHistory:output_type -> pkg.ClearHistoryResponse
	6,  // 8: pkg.Ai.GetInformation:output_type -> pkg.GetInformationResponse
	4,  // 9: pkg.Ai.ChangeModel:output_type -> pkg.ChangeModelResponse
	2,  // 10: pkg.Ai.GenerateImage:output_type -> pkg.GenerateImageResponse
	6,  // [6:11] is the sub-list for method output_type
	1,  // [1:6] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_protos_ai_proto_init() }
func file_protos_ai_proto_init() {
	if File_protos_ai_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_ai_proto_rawDesc), len(file_protos_ai_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_ai_proto_goTypes,
		DependencyIndexes: file_protos_ai_proto_depIdxs,
		EnumInfos:         file_protos_ai_proto_enumTypes,
		MessageInfos:      file_protos_ai_proto_msgTypes,
	}.Build()
	File_protos_ai_proto = out.File
	file_protos_ai_proto_goTypes = nil
	file_protos_ai_proto_depIdxs = nil
}
