// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.0
// source: protos/ai.proto

package aiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ModelType int32

const (
	ModelType_MODEL_UNSPECIFIED ModelType = 0
	ModelType_IMAGE_MODEL       ModelType = 1
	ModelType_TEXT_MODEL        ModelType = 2
)

// Enum value maps for ModelType.
var (
	ModelType_name = map[int32]string{
		0: "MODEL_UNSPECIFIED",
		1: "IMAGE_MODEL",
		2: "TEXT_MODEL",
	}
	ModelType_value = map[string]int32{
		"MODEL_UNSPECIFIED": 0,
		"IMAGE_MODEL":       1,
		"TEXT_MODEL":        2,
	}
)

func (x ModelType) Enum() *ModelType {
	p := new(ModelType)
	*p = x
	return p
}

func (x ModelType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ModelType) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_ai_proto_enumTypes[0].Descriptor()
}

func (ModelType) Type() protoreflect.EnumType {
	return &file_protos_ai_proto_enumTypes[0]
}

func (x ModelType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ModelType.Descriptor instead.
func (ModelType) EnumDescriptor() ([]byte, []int) {
	return file_protos_ai_proto_rawDescGZIP(), []int{0}
}

type GenerateImageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int64                  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Promt         string                 `protobuf:"bytes,2,opt,name=promt,proto3" json:"promt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateImageRequest) Reset() {
	*x = GenerateImageRequest{}
	mi := &file_protos_ai_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateImageRequest) ProtoMessage() {}

func (x *GenerateImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_ai_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateImageRequest.ProtoReflect.Descriptor instead.
func (*GenerateImageRequest) Descriptor() ([]byte, []int) {
	return file_protos_ai_proto_rawDescGZIP(), []int{0}
}

func (x *GenerateImageRequest) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *GenerateImageRequest) GetPromt() string {
	if x != nil {
		return x.Promt
	}
	return ""
}

type GenerateImageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateImageResponse) Reset() {
	*x = GenerateImageResponse{}
	mi := &file_protos_ai_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateImageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateImageResponse) ProtoMessage() {}

func (x *GenerateImageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_ai_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateImageResponse.ProtoReflect.Descriptor instead.
func (*GenerateImageResponse) Descriptor() ([]byte, []int) {
	return file_protos_ai_proto_rawDescGZIP(), []int{1}
}

func (x *GenerateImageResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type ChangeModelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          ModelType              `protobuf:"varint,1,opt,name=type,proto3,enum=pypkg.ModelType" json:"type,omitempty"`
	ModelName     string                 `protobuf:"bytes,2,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeModelRequest) Reset() {
	*x = ChangeModelRequest{}
	mi := &file_protos_ai_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeModelRequest) ProtoMessage() {}

func (x *ChangeModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_ai_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeModelRequest.ProtoReflect.Descriptor instead.
func (*ChangeModelRequest) Descriptor() ([]byte, []int) {
	return file_protos_ai_proto_rawDescGZIP(), []int{2}
}

func (x *ChangeModelRequest) GetType() ModelType {
	if x != nil {
		return x.Type
	}
	return ModelType_MODEL_UNSPECIFIED
}

func (x *ChangeModelRequest) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

type ChangeModelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeModelResponse) Reset() {
	*x = ChangeModelResponse{}
	mi := &file_protos_ai_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeModelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeModelResponse) ProtoMessage() {}

func (x *ChangeModelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_ai_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeModelResponse.ProtoReflect.Descriptor instead.
func (*ChangeModelResponse) Descriptor() ([]byte, []int) {
	return file_protos_ai_proto_rawDescGZIP(), []int{3}
}

func (x *ChangeModelResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *ChangeModelResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetInformationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInformationRequest) Reset() {
	*x = GetInformationRequest{}
	mi := &file_protos_ai_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInformationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInformationRequest) ProtoMessage() {}

func (x *GetInformationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_ai_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInformationRequest.ProtoReflect.Descriptor instead.
func (*GetInformationRequest) Descriptor() ([]byte, []int) {
	return file_protos_ai_proto_rawDescGZIP(), []int{4}
}

type GetInformationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatModel     string                 `protobuf:"bytes,1,opt,name=chat_model,json=chatModel,proto3" json:"chat_model,omitempty"`
	ImageModel    string                 `protobuf:"bytes,2,opt,name=image_model,json=imageModel,proto3" json:"image_model,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInformationResponse) Reset() {
	*x = GetInformationResponse{}
	mi := &file_protos_ai_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInformationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInformationResponse) ProtoMessage() {}

func (x *GetInformationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_ai_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInformationResponse.ProtoReflect.Descriptor instead.
func (*GetInformationResponse) Descriptor() ([]byte, []int) {
	return file_protos_ai_proto_rawDescGZIP(), []int{5}
}

func (x *GetInformationResponse) GetChatModel() string {
	if x != nil {
		return x.ChatModel
	}
	return ""
}

func (x *GetInformationResponse) GetImageModel() string {
	if x != nil {
		return x.ImageModel
	}
	return ""
}

type SuggestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int64                  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Suggest       string                 `protobuf:"bytes,2,opt,name=suggest,proto3" json:"suggest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuggestRequest) Reset() {
	*x = SuggestRequest{}
	mi := &file_protos_ai_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuggestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuggestRequest) ProtoMessage() {}

func (x *SuggestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_ai_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuggestRequest.ProtoReflect.Descriptor instead.
func (*SuggestRequest) Descriptor() ([]byte, []int) {
	return file_protos_ai_proto_rawDescGZIP(), []int{6}
}

func (x *SuggestRequest) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *SuggestRequest) GetSuggest() string {
	if x != nil {
		return x.Suggest
	}
	return ""
}

type SuggestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Request       string                 `protobuf:"bytes,2,opt,name=request,proto3" json:"request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuggestResponse) Reset() {
	*x = SuggestResponse{}
	mi := &file_protos_ai_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuggestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuggestResponse) ProtoMessage() {}

func (x *SuggestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_ai_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuggestResponse.ProtoReflect.Descriptor instead.
func (*SuggestResponse) Descriptor() ([]byte, []int) {
	return file_protos_ai_proto_rawDescGZIP(), []int{7}
}

func (x *SuggestResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *SuggestResponse) GetRequest() string {
	if x != nil {
		return x.Request
	}
	return ""
}

type ClearHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int64                  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearHistoryRequest) Reset() {
	*x = ClearHistoryRequest{}
	mi := &file_protos_ai_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearHistoryRequest) ProtoMessage() {}

func (x *ClearHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_ai_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearHistoryRequest.ProtoReflect.Descriptor instead.
func (*ClearHistoryRequest) Descriptor() ([]byte, []int) {
	return file_protos_ai_proto_rawDescGZIP(), []int{8}
}

func (x *ClearHistoryRequest) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type ClearHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearHistoryResponse) Reset() {
	*x = ClearHistoryResponse{}
	mi := &file_protos_ai_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearHistoryResponse) ProtoMessage() {}

func (x *ClearHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_ai_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearHistoryResponse.ProtoReflect.Descriptor instead.
func (*ClearHistoryResponse) Descriptor() ([]byte, []int) {
	return file_protos_ai_proto_rawDescGZIP(), []int{9}
}

func (x *ClearHistoryResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_protos_ai_proto protoreflect.FileDescriptor

const file_protos_ai_proto_rawDesc = "" +
	"\n" +
	"\x0fprotos/ai.proto\x12\x05pypkg\">\n" +
	"\x14GenerateImageRequest\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x03R\x03uid\x12\x14\n" +
	"\x05promt\x18\x02 \x01(\tR\x05promt\")\n" +
	"\x15GenerateImageResponse\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"Y\n" +
	"\x12ChangeModelRequest\x12$\n" +
	"\x04type\x18\x01 \x01(\x0e2\x10.pypkg.ModelTypeR\x04type\x12\x1d\n" +
	"\n" +
	"model_name\x18\x02 \x01(\tR\tmodelName\"?\n" +
	"\x13ChangeModelResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x17\n" +
	"\x15GetInformationRequest\"X\n" +
	"\x16GetInformationResponse\x12\x1d\n" +
	"\n" +
	"chat_model\x18\x01 \x01(\tR\tchatModel\x12\x1f\n" +
	"\vimage_model\x18\x02 \x01(\tR\n" +
	"imageModel\"<\n" +
	"\x0eSuggestRequest\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x03R\x03uid\x12\x18\n" +
	"\asuggest\x18\x02 \x01(\tR\asuggest\";\n" +
	"\x0fSuggestResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x18\n" +
	"\arequest\x18\x02 \x01(\tR\arequest\"'\n" +
	"\x13ClearHistoryRequest\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x03R\x03uid\"&\n" +
	"\x14ClearHistoryResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok*C\n" +
	"\tModelType\x12\x15\n" +
	"\x11MODEL_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vIMAGE_MODEL\x10\x01\x12\x0e\n" +
	"\n" +
	"TEXT_MODEL\x10\x022\xeb\x02\n" +
	"\x02Ai\x12;\n" +
	"\n" +
	"GetSuggest\x12\x15.pypkg.SuggestRequest\x1a\x16.pypkg.SuggestResponse\x12G\n" +
	"\fClearHistory\x12\x1a.pypkg.ClearHistoryRequest\x1a\x1b.pypkg.ClearHistoryResponse\x12M\n" +
	"\x0eGetInformation\x12\x1c.pypkg.GetInformationRequest\x1a\x1d.pypkg.GetInformationResponse\x12D\n" +
	"\vChangeModel\x12\x19.pypkg.ChangeModelRequest\x1a\x1a.pypkg.ChangeModelResponse\x12J\n" +
	"\rGenerateImage\x12\x1b.pypkg.GenerateImageRequest\x1a\x1c.pypkg.GenerateImageResponseB\x14Z\x12algobot.ai.v1;aiv1b\x06proto3"

var (
	file_protos_ai_proto_rawDescOnce sync.Once
	file_protos_ai_proto_rawDescData []byte
)

func file_protos_ai_proto_rawDescGZIP() []byte {
	file_protos_ai_proto_rawDescOnce.Do(func() {
		file_protos_ai_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_ai_proto_rawDesc), len(file_protos_ai_proto_rawDesc)))
	})
	return file_protos_ai_proto_rawDescData
}

var file_protos_ai_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_protos_ai_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_protos_ai_proto_goTypes = []any{
	(ModelType)(0),                 // 0: pypkg.ModelType
	(*GenerateImageRequest)(nil),   // 1: pypkg.GenerateImageRequest
	(*GenerateImageResponse)(nil),  // 2: pypkg.GenerateImageResponse
	(*ChangeModelRequest)(nil),     // 3: pypkg.ChangeModelRequest
	(*ChangeModelResponse)(nil),    // 4: pypkg.ChangeModelResponse
	(*GetInformationRequest)(nil),  // 5: pypkg.GetInformationRequest
	(*GetInformationResponse)(nil), // 6: pypkg.GetInformationResponse
	(*SuggestRequest)(nil),         // 7: pypkg.SuggestRequest
	(*SuggestResponse)(nil),        // 8: pypkg.SuggestResponse
	(*ClearHistoryRequest)(nil),    // 9: pypkg.ClearHistoryRequest
	(*ClearHistoryResponse)(nil),   // 10: pypkg.ClearHistoryResponse
}
var file_protos_ai_proto_depIdxs = []int32{
	0,  // 0: pypkg.ChangeModelRequest.type:type_name -> pypkg.ModelType
	7,  // 1: pypkg.Ai.GetSuggest:input_type -> pypkg.SuggestRequest
	9,  // 2: pypkg.Ai.ClearHistory:input_type -> pypkg.ClearHistoryRequest
	5,  // 3: pypkg.Ai.GetInformation:input_type -> pypkg.GetInformationRequest
	3,  // 4: pypkg.Ai.ChangeModel:input_type -> pypkg.ChangeModelRequest
	1,  // 5: pypkg.Ai.GenerateImage:input_type -> pypkg.GenerateImageRequest
	8,  // 6: pypkg.Ai.GetSuggest:output_type -> pypkg.SuggestResponse
	10, // 7: pypkg.Ai.ClearHistory:output_type -> pypkg.ClearHistoryResponse
	6,  // 8: pypkg.Ai.GetInformation:output_type -> pypkg.GetInformationResponse
	4,  // 9: pypkg.Ai.ChangeModel:output_type -> pypkg.ChangeModelResponse
	2,  // 10: pypkg.Ai.GenerateImage:output_type -> pypkg.GenerateImageResponse
	6,  // [6:11] is the sub-list for method output_type
	1,  // [1:6] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_protos_ai_proto_init() }
func file_protos_ai_proto_init() {
	if File_protos_ai_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_ai_proto_rawDesc), len(file_protos_ai_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_ai_proto_goTypes,
		DependencyIndexes: file_protos_ai_proto_depIdxs,
		EnumInfos:         file_protos_ai_proto_enumTypes,
		MessageInfos:      file_protos_ai_proto_msgTypes,
	}.Build()
	File_protos_ai_proto = out.File
	file_protos_ai_proto_goTypes = nil
	file_protos_ai_proto_depIdxs = nil
}
