env: local # or prod
storage_path: "./storage/storage.db"
# telegram token set in env variables - TELEGRAM_TOKEN
migrations_path: "./migrations"
grpc:
  host: "localhost"
  port: 50051
  timeout: 300s
rate_limit:
  fill_period: 800ms
  bucket_limit: 6