name: Build Windows Binary with Icon

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.23.3'

      - name: Add icon and build binary
        run: |
          cd ./cmd/algobot
          GOOS=windows GOARCH=amd64 go build -o ./algobot.exe 

      - name: build binary migrator
        run: |
          cd ./cmd/migrator
          GOOS=windows GOARCH=amd64 go build -o ./migrator.exe 

      - name: Upload Windows binary
        uses: actions/upload-artifact@v4
        with:
          name: binary
          path: |
            ./cmd/migrator/migrator.exe
            ./cmd/algobot/algobot.exe
            ./config/dev.yaml
