name: Build Windows Binary with Icon

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.23.3'

      - name: Install rsrc
        run: go install github.com/akavel/rsrc@latest

      - name: Add icon and build binary
        run: |
          cd ./cmd
          rsrc -ico ./icon.ico
          GOOS=windows GOARCH=amd64 go build -o ./cmd/algobot.exe 

      - name: Upload Windows binary
        uses: actions/upload-artifact@v4
        with:
          name: algobot.exe
          path: ./cmd/cmd/
